image: dockerhub.ebi.ac.uk/ega/ega-data-api-build-container:latest

services:
  - docker:dind

stages:
  - build
  - package

maven-build:
  stage: build
  script:
    - mvn test

docker-build:
  stage: package
  script:
    - mvn clean package "-DdockerRegistry=$CI_REGISTRY_IMAGE" "-Dimage.version=$CI_COMMIT_TAG" -P production -DskipTests
  only:
    - tags
