# Use phusion/baseimage as base image.
FROM phusion/baseimage:latest

# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

# custon build instructions here...
# Java: OpenJDK8
RUN apt-get update
RUN apt-get install -y software-properties-common python-software-properties
RUN add-apt-repository ppa:openjdk-r/ppa
RUN apt-get update
RUN apt-get -y install openjdk-8-jdk
ADD zuul-server-1.0.0.BUILD-SNAPSHOT.jar /zuul-server-1.0.0.BUILD-SNAPSHOT.jar
RUN mkdir /etc/service/ega_v3_zuul
ADD zuuld.sh /etc/service/ega_v3_zuul/run
RUN chmod +x /etc/service/ega_v3_zuul/run

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Port
EXPOSE 8051
